// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyaNqqF0XRG8_VdsmvjsTY6yBnRLSUL4w',
    appId: '1:658002885015:web:4cabcbab57aac3403becd2',
    messagingSenderId: '658002885015',
    projectId: 'transit-e86c6',
    authDomain: 'transit-e86c6.firebaseapp.com',
    databaseURL: 'https://transit-e86c6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'transit-e86c6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjTdLdpiXViBD4HflFDx81p4r2P25Qxko',
    appId: '1:658002885015:android:68c9cd5a4680a6053becd2',
    messagingSenderId: '658002885015',
    projectId: 'transit-e86c6',
    databaseURL: 'https://transit-e86c6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'transit-e86c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8bgtbAdXyuHix97M3DaQmc2q0X43Eb7w',
    appId: '1:658002885015:ios:e0a776c559a3fb013becd2',
    messagingSenderId: '658002885015',
    projectId: 'transit-e86c6',
    databaseURL: 'https://transit-e86c6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'transit-e86c6.firebasestorage.app',
    iosBundleId: 'com.example.appDevice1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8bgtbAdXyuHix97M3DaQmc2q0X43Eb7w',
    appId: '1:658002885015:ios:e0a776c559a3fb013becd2',
    messagingSenderId: '658002885015',
    projectId: 'transit-e86c6',
    databaseURL: 'https://transit-e86c6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'transit-e86c6.firebasestorage.app',
    iosBundleId: 'com.example.appDevice1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyaNqqF0XRG8_VdsmvjsTY6yBnRLSUL4w',
    appId: '1:658002885015:web:db6c07ad0004c9ea3becd2',
    messagingSenderId: '658002885015',
    projectId: 'transit-e86c6',
    authDomain: 'transit-e86c6.firebaseapp.com',
    databaseURL: 'https://transit-e86c6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'transit-e86c6.firebasestorage.app',
  );
}
